"""Reusable components for the Cortex management audit log use case."""

from .cortex_client import (
    CortexAuthenticationError,
    CortexClientConfig,
    CortexClientError,
    CortexConfigurationError,
    CortexHTTPError,
    CortexManagementAuditClient,
    build_authenticated_headers,
    build_management_audit_logs_payload,
    extract_records_from_payload,
    records_to_dataframe,
)
from .cortex_parser import CortexManagementAuditParser
from .feature_engineering import (
    build_anomaly_taxonomy_table,
    build_field_interpretation_table,
    build_schema_profile,
    build_window_features,
    link_events_to_anomalous_windows,
    normalize_management_audit_dataframe,
    prepare_detection_matrix,
    run_isolation_forest_detection,
    run_rrcf_detection,
    run_signal_review,
)
from .utils import (
    UseCasePaths,
    dataframe_to_csv,
    find_repo_root,
    json_dump,
    make_extraction_id,
    parse_datetime,
    resolve_time_window,
    resolve_usecase_paths,
    to_epoch_millis,
)

__all__ = [
    "CortexAuthenticationError",
    "CortexClientConfig",
    "CortexClientError",
    "CortexConfigurationError",
    "CortexHTTPError",
    "CortexManagementAuditClient",
    "CortexManagementAuditParser",
    "UseCasePaths",
    "build_anomaly_taxonomy_table",
    "build_authenticated_headers",
    "build_field_interpretation_table",
    "build_management_audit_logs_payload",
    "build_schema_profile",
    "build_window_features",
    "dataframe_to_csv",
    "extract_records_from_payload",
    "find_repo_root",
    "json_dump",
    "link_events_to_anomalous_windows",
    "make_extraction_id",
    "normalize_management_audit_dataframe",
    "parse_datetime",
    "prepare_detection_matrix",
    "records_to_dataframe",
    "resolve_time_window",
    "resolve_usecase_paths",
    "run_isolation_forest_detection",
    "run_rrcf_detection",
    "run_signal_review",
    "to_epoch_millis",
]
